FROM node:alpine3.18 as dependencies

WORKDIR /root/build

COPY . .

RUN npm install

ARG ARG_AWS_ACCESS_KEY
ARG ARG_AWS_SECRET_ACCESS_KEY
ARG ARG_AWS_REGION

ENV AWS_ACCESS_KEY_ID $ARG_AWS_ACCESS_KEY
ENV AWS_SECRET_ACCESS_KEY $ARG_AWS_SECRET_ACCESS_KEY
ENV AWS_REGION=$ARG_AWS_REGION

ENTRYPOINT ["sh", "-c", "_tasks/deploy.sh"]
