export const catalogue = [
    {
        exam: 'java-arrays',
        title: 'Java - Arrays',
        rating: '4.3',
        level: 'BEGINNER',
        duration: '20:00',
        shortDescription: `Arrays are a fundamental concept in Java. You should know them very well, even when they seem to be low-level.`,
        fullDescription: `Arrays are low-level, but you need to know them very well. 
        Looping, indexing and all that are crucial for your Java skills. With that knowledge, you can make better
        decisions if you should use ArrayList or LinkedList.`,
        maxQuestions: 7,
    },
    {
        exam: 'java-arraylist',
        title: 'Java - Lists',
        rating: '4.3',
        level: 'BEGINNER',
        duration: '20:00',
        shortDescription: `Everything about ArrayLists, Lists, LinkedLists, and all that.`,
        fullDescription: `The collections framework is a very important part of Java. 
            This exam will test your knowledge about ArrayLists, Lists, LinkedLists, and all that.`,
        maxQuestions: 7,
    },
    {
        exam: 'java-constructor',
        title: 'Java - Constructors',
        rating: '4.3',
        level: 'BEGINNER',
        duration: '20:00',
        shortDescription: `Constructors are essential for initializing objects in Java. Understanding constructors is crucial for mastering object-oriented programming.`,
        fullDescription: `Constructors are a fundamental part of Java, used to initialize objects and set up initial states. This exam will cover various aspects of constructors, including basic usage, constructors with arguments, the use of this and super keywords, default constructors, and constructor overloading. Mastering these concepts is crucial for writing efficient and effective Java programs. By the end of this exam, you will have a strong understanding of how to work with constructors and use them to create robust Java applications.`,
        maxQuestions: 5,
    },
    {
        exam: 'java-datatypes',
        title: 'Java - Datatypes',
        rating: '4.3',
        level: 'BEGINNER',
        duration: '20:00',
        shortDescription: `Understanding datatypes in Java is fundamental. This includes primitives, wrapper classes, autoboxing, and unboxing.`,
        fullDescription: `Datatypes are a core concept in Java, essential for any developer to understand. This exam will cover various aspects of datatypes, including primitives (such as int and boolean), wrapper classes (like Integer and Boolean), and the concepts of autoboxing and unboxing. Additionally, it will touch upon string manipulations and operations.`,    
        maxQuestions: 5,
    },
    {
        exam: 'java-exceptions',
        title: 'Java - Exceptions',
        rating: '4.3',
        level: 'BEGINNER',
        duration: '20:00',
        shortDescription: `Exceptions are an often misunderstood, but important concept in Java.`,
        fullDescription: `Exceptions are an often misunderstood, but important concept in Java. They come with a bit unusual syntax and require to think differently than usually.`,
        maxQuestions: 5,
    },
    {
        exam: 'java-jdbc',
        title: 'Java - JDBC Basics',
        rating: '4.3',
        level: 'BEGINNER',
        duration: '20:00',
        shortDescription: `Understanding JDBC is essential for database operations in Java.`,
        fullDescription: `JDBC is a crucial part of Java for interacting with relational databases. This exam covers the basics of JDBC, including how to use ResultSet, Statement, PreparedStatement, and handle auto-generated keys. You'll also learn about establishing connections, performing CRUD operations, handling SQL exceptions, and best practices.`,
        maxQuestions: 5,
    },
    {
        exam: 'sql-basics',
        title: 'SQL - Basics',
        rating: '4.3',
        level: 'BEGINNER',
        duration: '20:00',
        shortDescription: `Practice the foundational concepts of SQL.`,
        fullDescription: `SQL is essential for interacting with relational databases. This exam covers the foundational concepts of SQL, such as SELECT, INSERT, UPDATE, and DELETE.`,
        maxQuestions: 5,
    },
    {
        exam: 'spring-basics',
        title: 'Spring - Basics',
        rating: '4.3',
        level: 'BEGINNER',
        duration: '20:00',
        shortDescription: `Learn the fundamentals of Spring framework.`,
        fullDescription: `This exam covers the basics of Spring framework, including Spring stereotypes, dependency injection, request mappings, DispatcherServlet, and ApplicationContext. It also includes best practices and common pitfalls to avoid.`,
        maxQuestions: 5,
    },
]
