on:
  push:
    branches: [ main ]
name: Build docker image and deploy to S3
jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
            aws-region: eu-west-1          
        - name: Build, tag, and push image to Github Packages
          id: build-image-production
          env:
            IMAGE_TAG: ${{ github.sha }}
            REPOSITORY: ${{ github.repository }}
            IMAGE_NAME: ${{ github.repository }}:${{ github.sha }}
            TARGET_IMAGE_NAME: grobmeier_de:${{ github.sha }}
          run: |
            docker build -t $IMAGE_NAME -f Dockerfile .
            docker run -e AWS_REGION=eu-west-1 -e AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY }} -e AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_KEY }} $IMAGE_NAME
