on:
  push:
    branches: [ main ]
name: Build docker image and deploy to S3
jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Build, tag, and push image to Github Packages
          id: build-image-production
          env:
            IMAGE_TAG: ${{ github.sha }}
            REPOSITORY: ${{ github.repository }}
            IMAGE_NAME: ${{ github.repository }}:${{ github.sha }}
            TARGET_IMAGE_NAME: grobmeier_de:${{ github.sha }}
          run: |
            docker build -t $IMAGE_NAME -f Dockerfile-Deploy .
            docker run $IMAGE_NAME
